name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  fmt:
    name: rustfmt & miri (nightly)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt, miri
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: rustfmt (check)
        run: cargo +nightly fmt --all -- --check
      - name: miri (check)
        run: cargo +nightly miri test --all-features --lib --bins --no-fail-fast --workspace --exclude wincode-fuzz

  lint-test:
    name: clippy & tests (MSRV)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.84.1
          components: clippy
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: clippy (deny warnings)
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: clippy (alloc)
        run: cargo clippy --all-targets --features alloc -- -D warnings
      - name: tests
        run: cargo test --all-features --all-targets --no-fail-fast --workspace
      - name: test uuid no serde compat
        run: cargo test uuid --features alloc,uuid --all-targets --no-fail-fast --workspace

  fuzz:
    name: fuzz smoke check (nightly)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: rustfmt (fuzz)
        run: cargo +nightly fmt --manifest-path fuzz/Cargo.toml -- --check
      - name: clippy (fuzz)
        run: cargo +nightly clippy --manifest-path fuzz/Cargo.toml --all-targets -- -D warnings
      - uses: dtolnay/install@cargo-fuzz
      - run: cargo +nightly fuzz run roundtrip --no-trace-compares -- -max_len=$((5 << 20)) -max_total_time=60